"""empty message

Revision ID: 96a4730a74ce
Revises: c8931e7ce3a9
Create Date: 2021-10-01 12:01:49.777908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96a4730a74ce'
down_revision = 'c8931e7ce3a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipes_user_id_fkey', 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('recipes_user_id_fkey', 'recipes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
